### ISSUE TITLE
Issue running with Deno

### ISSUE THREAD

**Issue by bombillazo** [sindresorhus/yoctocolors#20]
We're importing some npm dependencies in deno using the `npm:` specifier, and we are getting this error when using `@inquirer/prompts` due to a sub-dependency:

```sh
error: Uncaught (in promise) TypeError: tty.WriteStream.prototype.hasColors is not a function
    at Object.<anonymous> (file:///Users/Projects/Code/app/node_modules/.deno/yoctocolors-cjs@2.1.1/node_modules/yoctocolors-cjs/index.js:5:45)
    at Object.<anonymous> (file:///Users/Projects/Code/app/node_modules/.deno/yoctocolors-cjs@2.1.1/node_modules/yoctocolors-cjs/index.js:94:4)
    at Module._compile (node:module:729:34)
    at Object.Module._extensions..js (node:module:743:10)
    at Module.load (node:module:654:32)
    at Function.Module._load (node:module:522:12)
    at Module.require (node:module:673:19)
    at require (node:module:787:16)
    at file:///Users/Projects/Code/app/node_modules/.deno/yoctocolors-cjs@2.1.1/node_modules/yoctocolors-cjs/index.js:3:13
make: *** [env] Error 1
```

**Comment by bombillazo** [comment]
Seems deno has not implemented the `node:tty` lib used here, so this lib wont work for deno
https://docs.deno.com/runtime/manual/node/compatibility/

<img width="701" alt="image" src="https://github.com/sindresorhus/yoctocolors/assets/44002321/e6f72551-f915-4773-824f-f3f974bb1d69">

**Comment by sindresorhus** [comment]
Relevant: https://github.com/denoland/deno/pull/22763

**Comment by sindresorhus** [comment]
I made the check graceful, so it at least doesn't throw on Deno, but Deno will have to merge https://github.com/denoland/deno/pull/22763 for colors to work there.
